WARN 7: [filename: 4_14_do_not_use_duplicate_names_warning_.py, line: 8]: 'func' already defined here: lineno=4
WARN 7: [filename: 4_14_do_not_use_duplicate_names_warning_.py, line: 17]: 'method' already defined here: lineno=14
